version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"  # доступ к localhost
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel  
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboars:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  pluginloader:
    build:
      context: .
      dockerfile: Dockerfile.pluginloader
    cap_add:
      - NET_RAW       # raw socket для ICMP
    container_name: pluginloader
    network_mode: "host"  # чтобы пингать localhost
    volumes:
      - ./configs:/app/configs
      - ./Plugins:/app/Plugins
    restart: unless-stopped
    user: root
    command: ["./PluginLoader"] 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/metrics", "||", "exit", "1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s